#!/bin/sh

VERSION=$(git describe --tags --match "v[0-9]*" HEAD 2>/dev/null)

if [ -n "$(git status --porcelain)" ]; then
    VERSION="${VERSION}-dirty"
fi

if [ -f "${1}" ]; then
    OLD=$(cat ${1} | sed 's/VERSION = //')
else
    OLD=""
fi

if [ "${VERSION}" != "${OLD}" ]; then
    echo >&2 "  Archived ${VERSION}"
    echo "ARCHIVED_VERSION = ${VERSION}"
fi
